In [2]:
import numpy as np 
from sklearn import datasets
from sklearn.linear_model import LinearRegression

d:\python\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [4]:
data = datasets.load_boston()
X = data['data']
y = data['target']
display(X.shape, y.shape)

(506, 13)

(506,)

In [6]:
X_train = X[:405]
y_train = y[:405]
X_test = X[405:]
y_test = y[405:]
display(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(405, 13)

(405,)

(101, 13)

(101,)

In [7]:
model = LinearRegression(fit_intercept=True)
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
model.coef_

array([-1.94651664e-01,  4.40677436e-02,  5.21447706e-02,  1.88823450e+00,
       -1.49475195e+01,  4.76119492e+00,  2.62339333e-03, -1.30091291e+00,
        4.60230476e-01, -1.55731325e-02, -8.11248033e-01, -2.18154708e-03,
       -5.31513940e-01])

In [10]:
 model.intercept_

30.183480140978663

In [12]:
model.predict(X_test).round(2)

array([ 4.25,  6.75, 21.36, 15.44, 23.75, 16.99, 22.37,  4.77, 12.52,
       -4.08, 14.75, 19.56,  9.12,  6.24, 20.55, 22.21, 20.68, 20.34,
       19.13, 19.84, 15.03, 21.26, 17.49, 19.35, 18.58, 23.25, 24.15,
       26.75, 22.69, 20.68, 18.62, 20.29, 14.38,  9.58, 14.17, 12.97,
       19.31, 20.83, 20.12, 14.35, 17.85, 20.73, 19.99, 19.2 , 20.33,
       23.53, 22.38, 20.89, 25.7 , 21.98, 22.21, 19.05, 19.01, 20.63,
       20.39, 23.3 , 22.65, 21.9 , 24.9 , 22.08, 20.32, 20.55, 19.29,
       17.89, 19.16, 22.01, 24.84, 24.64, 28.43, 17.63, 18.69, 22.61,
       12.09, 20.71, 22.99, 25.19, 29.38, 31.14, 22.73, 21.56, 24.51,
       21.48, 22.98, 10.34,  7.21,  2.61, 12.83, 14.97, 19.97, 20.13,
       16.22, 13.1 , 18.64, 20.96, 17.7 , 20.17, 23.75, 22.08, 28.17,
       26.56, 22.01])

In [13]:
y_test

array([ 5. , 11.9, 27.9, 17.2, 27.5, 15. , 17.2, 17.9, 16.3,  7. ,  7.2,
        7.5, 10.4,  8.8,  8.4, 16.7, 14.2, 20.8, 13.4, 11.7,  8.3, 10.2,
       10.9, 11. ,  9.5, 14.5, 14.1, 16.1, 14.3, 11.7, 13.4,  9.6,  8.7,
        8.4, 12.8, 10.5, 17.1, 18.4, 15.4, 10.8, 11.8, 14.9, 12.6, 14.1,
       13. , 13.4, 15.2, 16.1, 17.8, 14.9, 14.1, 12.7, 13.5, 14.9, 20. ,
       16.4, 17.7, 19.5, 20.2, 21.4, 19.9, 19. , 19.1, 19.1, 20.1, 19.9,
       19.6, 23.2, 29.8, 13.8, 13.3, 16.7, 12. , 14.6, 21.4, 23. , 23.7,
       25. , 21.8, 20.6, 21.2, 19.1, 20.6, 15.2,  7. ,  8.1, 13.6, 20.1,
       21.8, 24.5, 23.1, 19.7, 18.3, 21.2, 17.5, 16.8, 22.4, 20.6, 23.9,
       22. , 11.9])

In [15]:
model.score(X_test, y_test)

-0.25294153725445967

In [16]:
from sklearn.metrics import mean_squared_error

In [17]:
mean_squared_error(y_test, model.predict(X_test))

33.31360656409773

In [18]:
mean_squared_error(y_train, model.predict(X_train))

22.73718934348866