In [3]:
import numpy as np 

### numpy数字化python 研究数据

In [4]:
L = [1,2,3,4,5,6]
arr = np.array(L)
arr 

array([1, 2, 3, 4, 5, 6])

In [5]:
arr[[1,2]]

array([2, 3])

In [6]:
# 筛选出数组中大于等于3的数
conda = arr >= 3 
conda 
arr[conda]

array([3, 4, 5, 6])

### 数组的不同创建方式

In [7]:
# 创建10个值为1的数值
np.ones(shape=10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
# 个数为20个，值为3.14
np.full(shape=20, fill_value=3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14,
       3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [9]:
# 随机从0，100之间生成10个整数
np.random.randint(0, 100, size=10)

array([95,  1, 27, 94, 24, 71, 69, 17, 32, 68])

In [10]:
# 正态分布  平均值是0 标准差是1
np.random.randn(10) 

array([ 1.36912412, -0.82396453,  0.13400326,  0.37951817, -0.45827806,
       -0.09824817,  0.16337892, -0.92905658,  0.37499628,  2.20334566])

In [11]:
np.linspace(1, 99, 50)  # 等差数列

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
       79., 81., 83., 85., 87., 89., 91., 93., 95., 97., 99.])

In [16]:
np.set_printoptions(suppress=True)  # 不显示科学计数法
np.logspace(0, 10, base=2, num=11)  # 等比数列  base:多少的次幂  num：生成多少个数 默认的个数是50

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

In [18]:
np.random.randint(0, 10, size=(3, 5))  # 返回一个二维数组

array([[6, 3, 6, 1, 9],
       [9, 3, 6, 5, 5],
       [1, 6, 9, 9, 6]])

In [22]:
np.random.randint(0, 10, size=(2, 5, 3))  # 返回一个三维数组

array([[[2, 4, 7],
        [3, 3, 5],
        [3, 7, 3],
        [9, 6, 6],
        [2, 7, 6]],

       [[9, 2, 5],
        [4, 6, 8],
        [1, 0, 7],
        [1, 4, 7],
        [7, 7, 1]]])

### 数组的轴数，维度

In [24]:
arr = np.random.random(size=(3, 5))
arr

array([[0.39126896, 0.50967661, 0.01254126, 0.56601026, 0.54917718],
       [0.24635647, 0.04956348, 0.07549978, 0.4762372 , 0.73372208],
       [0.88459759, 0.6667065 , 0.03578946, 0.26475823, 0.56869226]])

In [25]:
arr.shape  # 形状

(3, 5)

In [26]:
arr.dtype  # 类型 float64

dtype('float64')

In [27]:
arr.size

15

In [28]:
arr.ndim # 维度

2

In [29]:
arr.itemsize  # 每个元素的大小  对应8个字节  64位 / 8

8

### 数组保存

In [30]:
arr = np.arange(0, 10, 2)  # 等差数列
arr 

array([0, 2, 4, 6, 8])

In [31]:
np.save('./data1', arr)  # 保存数据

In [32]:
np.load('./data1.npy')  #取出数据

array([0, 2, 4, 6, 8])

In [33]:
arr1 = np.logspace(0, 10, base=2, num=11)

In [34]:
np.savez('./data2.npz', x=arr, y=arr1)

In [35]:
np.load('./data2.npz')['x']  # 加载多个数据中的x

array([0, 2, 4, 6, 8])

In [36]:
np.load('./data2.npz')['y']  # 加载多个数据中的y

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

In [38]:
# 保存为csv文件  使用savetxt
arr = np.random.random(size=(3, 4))
arr

array([[0.46796539, 0.93193835, 0.35398898, 0.47037893],
       [0.89819324, 0.72081282, 0.22417376, 0.91621983],
       [0.67465691, 0.6430309 , 0.96837014, 0.08334618]])

In [40]:
np.savetxt('./data.csv', arr,delimiter=',')  # 逗号分割符

In [41]:
np.loadtxt('./data.csv', delimiter=',')

array([[0.46796539, 0.93193835, 0.35398898, 0.47037893],
       [0.89819324, 0.72081282, 0.22417376, 0.91621983],
       [0.67465691, 0.6430309 , 0.96837014, 0.08334618]])

### 数据类型

In [45]:
"""
整数：
浮点数：
字符串：
"""
arr = np.array([2, 4, 5], dtype=np.int16)
arr

array([2, 4, 5], dtype=int16)

In [44]:
arr = np.array([2, 4, 5], dtype=np.int32)
arr

array([2, 4, 5])

In [49]:
arr = np.random.randint(1, 100, size=(100, 50), dtype=np.int8)
np.save('./data3_int8', arr)

In [50]:
arr = np.random.randint(1, 100, size=(100, 50), dtype=np.int64)
np.save('./data4_int64', arr)

### uint8 无符号 没有负数 没有负数   0-255

In [54]:
arr=np.random.randint(1, 100, size=(100, 50),dtype=np.uint8)
arr

array([[88, 88, 39, ..., 98, 50,  7],
       [74, 41, 63, ...,  9, 63, 20],
       [72,  8, 77, ..., 38,  7, 92],
       ...,
       [54, 37, 81, ..., 69, 79, 48],
       [27, 84, 56, ..., 99, 26, 49],
       [73, 36, 56, ..., 32, 84, 31]], dtype=uint8)

In [57]:
# 转换数据类型 astype
arr1 = arr.astype('float32')

In [58]:
arr1.dtype

dtype('float32')

In [59]:
arr = [1,2,3,4,5,5,6]
# 使用asarray将列表转为数组
np.asarray(arr)

array([1, 2, 3, 4, 5, 5, 6])

### 数组运算

In [61]:
arr=np.random.randint(1, 100, size=(100, 50))

In [62]:
arr - 5

array([[17, 91, 48, ..., 12, 33, 72],
       [45, 93, 41, ..., 36, 86, 52],
       [69, 78,  7, ..., 61,  2, 75],
       ...,
       [80, 17, 54, ..., 86, 24, 24],
       [50, 86, 28, ..., 87, 50, 30],
       [35, 77, 92, ..., 17, 38, 69]])

In [63]:
arr * 5

array([[110, 480, 265, ...,  85, 190, 385],
       [250, 490, 230, ..., 205, 455, 285],
       [370, 415,  60, ..., 330,  35, 400],
       ...,
       [425, 110, 295, ..., 455, 145, 145],
       [275, 455, 165, ..., 460, 275, 175],
       [200, 410, 485, ..., 110, 215, 370]])

In [64]:
arr ** 2

array([[ 484, 9216, 2809, ...,  289, 1444, 5929],
       [2500, 9604, 2116, ..., 1681, 8281, 3249],
       [5476, 6889,  144, ..., 4356,   49, 6400],
       ...,
       [7225,  484, 3481, ..., 8281,  841,  841],
       [3025, 8281, 1089, ..., 8464, 3025, 1225],
       [1600, 6724, 9409, ...,  484, 1849, 5476]], dtype=int32)

In [65]:
arr > 5

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [66]:
arr == 5

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

### 多维数组

In [74]:
arr = np.array([[1,2,3], [3,4,5], [4,5,6]])
arr

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [87]:
arr[1, [2, 2]]

array([5, 5])

In [84]:
arr[0, [1, 2]]

array([2, 3])

In [95]:
arr[:, 1:2]

array([[2],
       [4],
       [5]])

In [101]:
arr[2, [1, 2]]

array([77,  6])

In [100]:
arr

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 4, 77,  6]])

### 花式索引

整数进行花式索引，和切片不一样，总是把数据复制到新的数组中

np.ix_函数，能把两个一维数组 转换为 一个用于选取方形区域的索引器

原理： np.ix_函数就是输入两个数组，产生笛卡尔积的映射关系

In [102]:
arr = np.random.randint(1, 40, size=(5, 8))
arr

array([[28, 21,  3, 23, 22, 35, 10,  1],
       [ 3, 28, 38, 12, 20,  1, 30, 24],
       [11,  1, 18, 18, 12, 34,  3, 13],
       [15, 37, 13, 37, 37, 36, 19, 27],
       [17, 35, 33, 21,  2, 21, 32, 25]])

In [104]:
arr[2, [3,4]]  # 花式索引

array([18, 12])

In [106]:
arr[[2, 3, 4]]  # 花式索引

array([[11,  1, 18, 18, 12, 34,  3, 13],
       [15, 37, 13, 37, 37, 36, 19, 27],
       [17, 35, 33, 21,  2, 21, 32, 25]])

In [109]:
conda1 = arr > 50
conda2 = arr < 50  
# 使用|进行多种索引的拼接
conda = conda1 | conda2
arr[conda]  #  花式索引

array([28, 21,  3, 23, 22, 35, 10,  1,  3, 28, 38, 12, 20,  1, 30, 24, 11,
        1, 18, 18, 12, 34,  3, 13, 15, 37, 13, 37, 37, 36, 19, 27, 17, 35,
       33, 21,  2, 21, 32, 25])

In [110]:
arr[np.ix_([1,2,3], [2,3])] # 这种方式等效于 arr[[1,2,3], [:,[2:3]]] 产生了笛卡尔效应

array([[38, 12],
       [18, 18],
       [13, 37]])